import zlib
import sqlite3

# There are 3 classes, they are all basically the same

class WikiDB:
    def __init__(self, filename):
	# This is the sqlite db for the main db file (generated by wikiparse.py)
	# I create a table called articles and there are 4 arguments
	# pageid: unique key for every article
	# title: for convenience
	# categories: can quickly check if some value is in the categories
	# zarticle: compressed article
        self.conn = sqlite3.connect(filename)
        self.conn.execute("""
        CREATE TABLE IF NOT EXISTS articles (
          pageid integer,
          title text,
          categories text,
          zarticle text)""")
        self.conn.commit()
        self.pending = 0  # Only commits the data every 100 articles for efficiency

    def maybe_commit(self):
        self.pending += 1
        if self.pending > 100:
            self.commit()

    def commit(self):
	# This is called every 100 maybe_commits() and when you finish iterating over the xml dump
        self.conn.commit()
        self.pending = 0

    def insert(self, pageid, title, categories, article):
	# Compresses article and inserts values into table
        zarticle = zlib.compress(article.encode('utf-8'))
        self.conn.execute("""
          INSERT INTO articles VALUES (?, ?, ?, ?);
        """, (pageid, title, categories, zarticle))
        self.maybe_commit()

    def __iter__(self):
	# Decopresses and generates (pageid, title, categories, zarticle)
        for (pageid, title, categories, zarticle) in self.conn.execute('''
        SELECT * FROM articles;
      '''):
            article = zlib.decompress(zarticle).decode('utf-8')
            yield (pageid, title, categories, article)
    def iterCatergories(self):
	# Generates the categories
        for categories in self.conn.execute("""
        SELECT categories FROM articles;
        """):
            yield
    def iterRandom(self, e):
	# Iterates over  e uniformly random articles
        for (pageid, title, categories, zarticle) in self.conn.execute('''
                SELECT * FROM articles order by random() limit {};
              '''.format(str(e))):
            article = zlib.decompress(zarticle).decode('utf-8')
            yield (pageid, title, categories, article)

class WikiDBWithGenderAndInfobox:
    def __init__(self, filename):
	# This is the same thing as WikiDB but more specific
	# Here I look at characters, gender and the infobox arguments 
        self.conn = sqlite3.connect(filename)
        self.conn.execute("""
        CREATE TABLE IF NOT EXISTS articles (
          pageid integer,
          title text,
          categories text,
          chars integer,
          gender text,
          infoboxArgs text)""")
        self.conn.commit()
        self.pending = 0

    def maybe_commit(self):
        self.pending += 1
        if self.pending > 100:
            self.commit()

    def commit(self):
        self.conn.commit()
        self.pending = 0

    def insert(self, pageid, title, categories, chars, gender, infoboxArgs):
        self.conn.execute("""
          INSERT INTO articles VALUES (?, ?, ?, ?, ?, ?);
        """, (pageid, title, categories, chars, gender, infoboxArgs))
        self.maybe_commit()

    def __iter__(self):
        for (pageid, title, categories, chars, gender, infoboxArgs) in self.conn.execute('''
        SELECT * FROM articles;
      '''):
            yield (pageid, title, categories, chars, gender, infoboxArgs)
    def iterCatergories(self):
        for categories in self.conn.execute("""
        SELECT categories FROM articles;
        """):
            yield categories
    def iterRandom(self, e):
        for (pageid, title, categories, chars, gender, infoboxArgs) in self.conn.execute('''
                SELECT * FROM articles order by random() limit {};
              '''.format(str(e))):
            yield (pageid, title, categories, chars, gender, infoboxArgs)

class WikiDBWithGenderAndInfobox2:
    def __init__(self, filename):
        self.conn = sqlite3.connect(filename)
        self.conn.execute("""
        CREATE TABLE IF NOT EXISTS articles (
          pageid integer,
          title text,
          categories text,
          chars integer,
          gender text,
          infoboxArgs text,
          infobox text
          )""")
        self.conn.commit()
        self.pending = 0

    def maybe_commit(self):
        self.pending += 1
        if self.pending > 100:
            self.commit()

    def commit(self):
        self.conn.commit()
        self.pending = 0

    def insert(self, pageid, title, categories, chars, gender, infoboxArgs, infobox):
        self.conn.execute("""
          INSERT INTO articles VALUES (?, ?, ?, ?, ?, ?, ?);
        """, (pageid, title, categories, chars, gender, infoboxArgs, infobox))
        self.maybe_commit()

    def __iter__(self):
        for (pageid, title, categories, chars, gender, infoboxArgs, infobox) in self.conn.execute('''
        SELECT * FROM articles;
      '''):
            yield (pageid, title, categories, chars, gender, infoboxArgs, infobox)
    def iterCatergories(self):
        for categories in self.conn.execute("""
        SELECT categories FROM articles;
        """):
            yield categories
    def iterRandom(self, e):
        for (pageid, title, categories, chars, gender, infoboxArgs, infobox) in self.conn.execute('''
                SELECT * FROM articles order by random() limit {};
              '''.format(str(e))):
            yield (pageid, title, categories, chars, gender, infoboxArgs, infobox)

